= Store

* Behavior-Subjects
* Redux/Flux
  ** Effects: danger zone

Da der Store stateful und potentiell eine große Datenmenge aufnehmen kann, ist es sinnvoll, sich Gedanken über die Lebensdauer des Store zu machen.
Die Lebensdauer kann an folgenden Stellen beeinflusst werden:

Im Module:: Wird der Store bei den Providers eingetragen, wird die Klasse für die zugehörigen Komponenten des jeweiligen Moduls bereitgestellt.
Allerdings wird der Store nicht destroyed, wenn zu einem View navigiert und die Komponenten destroyed werden.
In der Komponente:: Wird der Store in einer Komponenten bei den Providers eingetragen, wird der Store destroyed, wenn die Komponenten destroyed wird.
Das kann aber auch unerwünscht sein, wenn der Store zwischen mehreren Komponenten geteilt werden soll.
In einer Wrapper-Komponente:: Eine weitere Möglichkeit die Lebensdauer des Stores zu beschränken, besteht darin, eine Wrapper-Komponenten einzuführen, die den Store in ihre Providers aufnimmt und über ein `<router-outlet></router-outlet>` und zugehöriges Routing die gewünschten Komponenten zur Anzeige bringt.

[source,typescript]
----
@Injectable()
export abstract class AbstractStore<T> implements OnDestroy {
  private _value$: BehaviorSubject<T>;

  public get value$(): Observable<T> {
    return this._value$.asObservable();
  }

  protected constructor(initialValue: T) {
    this._value$ = new BehaviorSubject<T>(initialValue);
  }

  update(config: T): void {
    if (isDevMode()) {
      deepFreeze(config);
    }
    this._value$.next(config);
  }

  getInstant(): T {
    return this._value$.getValue();
  }

  ngOnDestroy(): void {
    this._value$.complete();
  }
}
----

Ein konkreter Store kann dann z.B. wie folgt implementiert werden.
Diese Implementierung entfernt das erste Element welches `undefined` wäre.

[source,typescript]
----
@Injectable()
export class MyDataStore extends AbstractStore<MyData> {
  private readonly skipFirstValue$ = super.value$.pipe(skip(1), shareReplay(1));

  public get value$(): Observable<MyData> {
    return this.skipFirstValue$;
  }

  constructor() {
    super(undefined);
  }
}
----
